fix a bug in ildg conf reader and add stabilized Wilson fermion confs…
LatticeQCD/SIMULATeQCD pull request #120
Opened 2023-01-27 10:55 UTC by kimjangho1120

It was hardcoded to read the nersc conf when reading the ildg conf in the gradient flow application.
Added "if else" for all supported formats to src/application/main_gradientFlow.cpp.
But still there is checksum error when reading ildg conf.
Also, a stabilized Wilson Fermion (openqcd) reader has been implemented.
There are no checksum errors in this format.

2023-01-31 15:13 UTC, luhuhis requested changes
Looks good otherwise

2023-01-31 15:13 UTC, luhuhis commented on src/applications/main_CheckConf.cpp
> +    rootLogger.info("Plaquette = ", plaq * 3);
This should be reverted

2023-01-31 15:27 UTC, clarkedavida commented
Before merging this in, I would like to see a few things fixed:
- [ ] add a small 8^3x4 OPENQCD test to https://github.com/LatticeQCD/SIMULATeQCD/blob/main/src/testing/main_confReadWriteTest.cpp
- [ ] remove this plaquette*3 that luis pointed out
- [ ] please verify that `make everything` still works and that the tests pass!

I am going to look into the ILDG read problem.

2023-05-09 20:40 UTC, clarkedavida commented
These are already being taken care of in #123.

2023-05-09 20:40 UTC, closed without merging